```{r}
library(dplyr)
ElectionPoll<-read.csv("polls_us_election_2016.csv", header = TRUE)
head(ElectionPoll)
```

```{r}
#提取出pollster和grade两列，并把相同行合并
pollster_grade <- distinct(subset(ElectionPoll, select = c("pollster","grade")))
pollster_grade
```

```{r}
pollster_grade1 <- na.omit(pollster_grade) #删除掉grade是NA的那一整行数据
pollster_grade1
```

```{r}
grouped_data <- pollster_grade1 %>%
  group_by(pollster) %>%
  summarise(number_of_grades = n_distinct(grade))
grouped_data #根据结果可以看出每一种pollster只有一种评级
```

```{r}
summary_data <- pollster_grade1 %>%
  group_by(grade, pollster) %>%
  summarise(count = n(), .groups = 'drop')
summary_data
```

```{r}
#把grade一列转换成因子型数据
grade_as_factor <- as.factor(pollster_grade$grade)
grade_as_factor
```

```{r pie chart, fig.width=3, fig.height=3}
#绘制grade类别的饼图，自动去掉NA数据
category_counts <- table(grade_as_factor)
percentages <- (category_counts / sum(category_counts))*100
labels <- paste(names(category_counts), "\n", round(percentages, 1), "%", sep="")
pie(category_counts, labels = labels, main = "Pie Chart of Categories")
```